name: Arch Linux Docker Image Build for WSL2 Kernel Builds

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        include:
          - tag: build

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & Push Latest Image
        id: build_image
        uses: docker/build-push-action@master
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nevuly-dev-base:${{ matrix.tag }}

      - name: Image Digest
        run: echo ${{ steps.build_image.outputs.digest }}
