name: Arch Linux Docker image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        include:
          - tag: arch
            dockerfile: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push latest
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: dockerfiles/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nevuly-dev-base:${{ matrix.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
